init = "init.sh"
run = "run.sh"
validate = "validate.sh"
clean = "clean.sh"
explorePolicy = "etcd"

notCleanIfValidationFail= "true"

[explorePolicyParam]
 minBound = 100
 maxBound = 1000

# storageType = "mongodb"
